[package]
name = "cboe-pcap-receiver"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ctrlc = "3.2"
libc = "0.2"

# Flux-inspired high-performance dependencies
tokio = { version = "1.0", features = ["full"] }
socket2 = "0.5"
crossbeam-queue = "0.3"
dashmap = "6.0"
parking_lot = "0.12"
memmap2 = "0.9"
smallvec = "1.13"
arrayvec = "0.7"
atomic = "0.6"
flume = "0.11"
rayon = "1.10"
wide = "0.7"
core_affinity = "0.8"
num_cpus = "1.16"
lazy_static = "1.4"

# Optional allocators for performance
jemallocator = { version = "0.5", optional = true }
mimalloc = { version = "0.1", optional = true }

[features]
default = []
jemalloc = ["dep:jemallocator"]
mimalloc = ["dep:mimalloc"]
simd = []

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
