[package]
name = "cboe-pcap-receiver"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ctrlc = "3.2"
libc = "0.2"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3